{
    'name': 'Hospital Management',
    'version': '11.0.0.0',
    'category': '',
    'summary': 'Manage the Hospital',
    'sequence': '10',
    'license': '',
    'author': 'Kasim saifi',
    'maintainer': '',
    'depends': [ 'mail', 'purchase', 'sale'],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'data/data.xml',
        'data/cron.xml',
        'data/mail_tamplate.xml',
        'views/patient.xml',
        'views/appointment.xml',
        'views/doctor.xml',
        'views/lab.xml',
        'views/company.xml',
        'views/receipt_flow.xml',
        'views/parameter.xml',
        'views/purchase_rfq.xml',
        'views/purchase_order.xml',
        'views/sale_rqf.xml',
        # 'views/job_view.xml',
        'views/sale_inquiries.xml',
        'reports/report.xml',
        'reports/sale_report.xml',
        'reports/text_invoice.xml',
        'reports/patient_card.xml',
        'wizards/create_appointment.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
